export interface Question {
  id: number;
  text: string;
  expectedAnswer: string;
  type: 'phoneme' | 'word' | 'sentence' | 'number' | 'calculation';
}

// Dyslexia questions organized by grade (1-12)
export const dyslexiaQuestionsByGrade: Record<number, Question[]> = {
  1: [
    { id: 1, text: 'Say the word: "CAT"', expectedAnswer: 'cat', type: 'word' },
    { id: 2, text: 'Say the word: "DOG"', expectedAnswer: 'dog', type: 'word' },
    { id: 3, text: 'What sound does "B" make?', expectedAnswer: 'buh', type: 'phoneme' },
    { id: 4, text: 'Say the word: "SUN"', expectedAnswer: 'sun', type: 'word' },
    { id: 5, text: 'Say the letters: A, B, C', expectedAnswer: 'a b c', type: 'phoneme' },
    { id: 6, text: 'What rhymes with "CAT"?', expectedAnswer: 'bat hat mat', type: 'phoneme' },
    { id: 7, text: 'Say the word: "RED"', expectedAnswer: 'red', type: 'word' },
    { id: 8, text: 'Read: "I see a dog"', expectedAnswer: 'i see a dog', type: 'sentence' },
  ],
  2: [
    { id: 1, text: 'Say the word: "APPLE"', expectedAnswer: 'apple', type: 'word' },
    { id: 2, text: 'Say the word: "HAPPY"', expectedAnswer: 'happy', type: 'word' },
    { id: 3, text: 'Say the sounds in "STOP" (S-T-O-P)', expectedAnswer: 's t o p', type: 'phoneme' },
    { id: 4, text: 'Read: "The cat is big"', expectedAnswer: 'the cat is big', type: 'sentence' },
    { id: 5, text: 'Say the word: "YELLOW"', expectedAnswer: 'yellow', type: 'word' },
    { id: 6, text: 'What sound does "PH" make?', expectedAnswer: 'f', type: 'phoneme' },
    { id: 7, text: 'Say the word: "FRIEND"', expectedAnswer: 'friend', type: 'word' },
    { id: 8, text: 'Read: "We play in the park"', expectedAnswer: 'we play in the park', type: 'sentence' },
  ],
  3: [
    { id: 1, text: 'Say the word: "BUTTERFLY"', expectedAnswer: 'butterfly', type: 'word' },
    { id: 2, text: 'Say the word: "ELEPHANT"', expectedAnswer: 'elephant', type: 'word' },
    { id: 3, text: 'Say the sounds in "STREAM"', expectedAnswer: 's t r e a m', type: 'phoneme' },
    { id: 4, text: 'Read: "The quick brown fox jumps"', expectedAnswer: 'the quick brown fox jumps', type: 'sentence' },
    { id: 5, text: 'Say the word: "CHOCOLATE"', expectedAnswer: 'chocolate', type: 'word' },
    { id: 6, text: 'Say these letters: B, D, P, Q', expectedAnswer: 'b d p q', type: 'phoneme' },
    { id: 7, text: 'Say the word: "BEAUTIFUL"', expectedAnswer: 'beautiful', type: 'word' },
    { id: 8, text: 'Read: "She went to the library yesterday"', expectedAnswer: 'she went to the library yesterday', type: 'sentence' },
  ],
  4: [
    { id: 1, text: 'Say the word: "ENCYCLOPEDIA"', expectedAnswer: 'encyclopedia', type: 'word' },
    { id: 2, text: 'Say the word: "MAGNIFICENT"', expectedAnswer: 'magnificent', type: 'word' },
    { id: 3, text: 'Identify the silent letters in "KNIGHT"', expectedAnswer: 'k g h', type: 'phoneme' },
    { id: 4, text: 'Read: "The mysterious castle stood on the hilltop"', expectedAnswer: 'the mysterious castle stood on the hilltop', type: 'sentence' },
    { id: 5, text: 'Say the word: "PRONUNCIATION"', expectedAnswer: 'pronunciation', type: 'word' },
    { id: 6, text: 'Say the prefix and root in "UNHAPPY"', expectedAnswer: 'un happy', type: 'phoneme' },
    { id: 7, text: 'Say the word: "GOVERNMENT"', expectedAnswer: 'government', type: 'word' },
    { id: 8, text: 'Read: "Scientists discovered a new species of butterfly"', expectedAnswer: 'scientists discovered a new species of butterfly', type: 'sentence' },
  ],
  5: [
    { id: 1, text: 'Say the word: "PHENOMENON"', expectedAnswer: 'phenomenon', type: 'word' },
    { id: 2, text: 'Say the word: "SOPHISTICATED"', expectedAnswer: 'sophisticated', type: 'word' },
    { id: 3, text: 'Break down "UNBELIEVABLE" into syllables', expectedAnswer: 'un be liev a ble', type: 'phoneme' },
    { id: 4, text: 'Read: "The expedition traveled through treacherous mountain passes"', expectedAnswer: 'the expedition traveled through treacherous mountain passes', type: 'sentence' },
    { id: 5, text: 'Say the word: "BIBLIOGRAPHY"', expectedAnswer: 'bibliography', type: 'word' },
    { id: 6, text: 'Identify all the consonant blends in "STRENGTH"', expectedAnswer: 'str ngth', type: 'phoneme' },
    { id: 7, text: 'Say the word: "CONSCIENTIOUS"', expectedAnswer: 'conscientious', type: 'word' },
    { id: 8, text: 'Read: "The archaeological findings revealed ancient civilizations"', expectedAnswer: 'the archaeological findings revealed ancient civilizations', type: 'sentence' },
  ],
  6: [
    { id: 1, text: 'Say the word: "IDIOSYNCRATIC"', expectedAnswer: 'idiosyncratic', type: 'word' },
    { id: 2, text: 'Say the word: "METAMORPHOSIS"', expectedAnswer: 'metamorphosis', type: 'word' },
    { id: 3, text: 'Break down "ANTIDISESTABLISHMENTARIANISM" into parts', expectedAnswer: 'anti dis establish ment arian ism', type: 'phoneme' },
    { id: 4, text: 'Read: "The unprecedented technological advancement revolutionized communication"', expectedAnswer: 'the unprecedented technological advancement revolutionized communication', type: 'sentence' },
    { id: 5, text: 'Say the word: "ONOMATOPOEIA"', expectedAnswer: 'onomatopoeia', type: 'word' },
    { id: 6, text: 'Identify the Greek root in "PHILOSOPHY"', expectedAnswer: 'philo sophia', type: 'phoneme' },
    { id: 7, text: 'Say the word: "RECONNAISSANCE"', expectedAnswer: 'reconnaissance', type: 'word' },
    { id: 8, text: 'Read: "The constitutional amendment required congressional ratification"', expectedAnswer: 'the constitutional amendment required congressional ratification', type: 'sentence' },
  ],
  7: [
    { id: 1, text: 'Say the word: "ENTREPRENEURSHIP"', expectedAnswer: 'entrepreneurship', type: 'word' },
    { id: 2, text: 'Say the word: "QUINTESSENTIAL"', expectedAnswer: 'quintessential', type: 'word' },
    { id: 3, text: 'Identify Latin roots in "CIRCUMNAVIGATE"', expectedAnswer: 'circum navigate', type: 'phoneme' },
    { id: 4, text: 'Read: "The juxtaposition of contrasting elements created a compelling narrative"', expectedAnswer: 'the juxtaposition of contrasting elements created a compelling narrative', type: 'sentence' },
    { id: 5, text: 'Say the word: "SERENDIPITOUS"', expectedAnswer: 'serendipitous', type: 'word' },
    { id: 6, text: 'Break down "ELECTROMAGNETIC" morphologically', expectedAnswer: 'electro magnetic', type: 'phoneme' },
    { id: 7, text: 'Say the word: "PERSPICACIOUS"', expectedAnswer: 'perspicacious', type: 'word' },
    { id: 8, text: 'Read: "The philanthropic organization implemented sustainable development initiatives"', expectedAnswer: 'the philanthropic organization implemented sustainable development initiatives', type: 'sentence' },
  ],
  8: [
    { id: 1, text: 'Say the word: "SUPERCALIFRAGILISTICEXPIALIDOCIOUS"', expectedAnswer: 'supercalifragilisticexpialidocious', type: 'word' },
    { id: 2, text: 'Say the word: "PSYCHOPHYSIOLOGICAL"', expectedAnswer: 'psychophysiological', type: 'word' },
    { id: 3, text: 'Identify Greek and Latin prefixes in "TRANSCONTINENTAL"', expectedAnswer: 'trans continental', type: 'phoneme' },
    { id: 4, text: 'Read: "The epistemological discourse examined fundamental paradigms of knowledge acquisition"', expectedAnswer: 'the epistemological discourse examined fundamental paradigms of knowledge acquisition', type: 'sentence' },
    { id: 5, text: 'Say the word: "VERISIMILITUDE"', expectedAnswer: 'verisimilitude', type: 'word' },
    { id: 6, text: 'Analyze the morphemes in "UNCHARACTERISTICALLY"', expectedAnswer: 'un character istic ally', type: 'phoneme' },
    { id: 7, text: 'Say the word: "ANTIDISESTABLISHMENTARIANISM"', expectedAnswer: 'antidisestablishmentarianism', type: 'word' },
    { id: 8, text: 'Read: "The socioeconomic implications of globalization necessitate comprehensive policy frameworks"', expectedAnswer: 'the socioeconomic implications of globalization necessitate comprehensive policy frameworks', type: 'sentence' },
  ],
  9: [
    { id: 1, text: 'Say the word: "OTORHINOLARYNGOLOGY"', expectedAnswer: 'otorhinolaryngology', type: 'word' },
    { id: 2, text: 'Say the word: "INCOMPREHENSIBILITIES"', expectedAnswer: 'incomprehensibilities', type: 'word' },
    { id: 3, text: 'Analyze etymology of "DEMOCRACY"', expectedAnswer: 'demos kratos', type: 'phoneme' },
    { id: 4, text: 'Read: "The hermeneutical interpretation of literary texts requires contextual understanding of historical paradigms"', expectedAnswer: 'the hermeneutical interpretation of literary texts requires contextual understanding of historical paradigms', type: 'sentence' },
    { id: 5, text: 'Say the word: "COMPARTMENTALIZATION"', expectedAnswer: 'compartmentalization', type: 'word' },
    { id: 6, text: 'Identify all affixes in "DEINSTITUTIONALIZATION"', expectedAnswer: 'de institution al ization', type: 'phoneme' },
    { id: 7, text: 'Say the word: "COUNTERREVOLUTIONARY"', expectedAnswer: 'counterrevolutionary', type: 'word' },
    { id: 8, text: 'Read: "The phenomenological approach to consciousness explores the intrinsic nature of subjective experience"', expectedAnswer: 'the phenomenological approach to consciousness explores the intrinsic nature of subjective experience', type: 'sentence' },
  ],
  10: [
    { id: 1, text: 'Say the word: "PSYCHONEUROIMMUNOLOGY"', expectedAnswer: 'psychoneuroimmunology', type: 'word' },
    { id: 2, text: 'Say the word: "ELECTROENCEPHALOGRAPHY"', expectedAnswer: 'electroencephalography', type: 'word' },
    { id: 3, text: 'Analyze the compound structure of "MULTIDIMENSIONALITY"', expectedAnswer: 'multi dimension ality', type: 'phoneme' },
    { id: 4, text: 'Read: "The epistemological foundations of empiricism contrast fundamentally with rationalist philosophical traditions"', expectedAnswer: 'the epistemological foundations of empiricism contrast fundamentally with rationalist philosophical traditions', type: 'sentence' },
    { id: 5, text: 'Say the word: "BIOTECHNOLOGICAL"', expectedAnswer: 'biotechnological', type: 'word' },
    { id: 6, text: 'Identify derivational morphemes in "UNCONSTITUTIONALLY"', expectedAnswer: 'un constitution al ly', type: 'phoneme' },
    { id: 7, text: 'Say the word: "INTERNATIONALIZATION"', expectedAnswer: 'internationalization', type: 'word' },
    { id: 8, text: 'Read: "The methodological rigor of quantitative research paradigms ensures replicability and empirical validity"', expectedAnswer: 'the methodological rigor of quantitative research paradigms ensures replicability and empirical validity', type: 'sentence' },
  ],
  11: [
    { id: 1, text: 'Say the word: "TRANSUBSTANTIATION"', expectedAnswer: 'transubstantiation', type: 'word' },
    { id: 2, text: 'Say the word: "DECONTEXTUALIZATION"', expectedAnswer: 'decontextualization', type: 'word' },
    { id: 3, text: 'Trace the etymological evolution of "METAMORPHOSIS"', expectedAnswer: 'meta morphe osis', type: 'phoneme' },
    { id: 4, text: 'Read: "The ontological presuppositions underlying existentialist philosophy challenge conventional metaphysical assumptions"', expectedAnswer: 'the ontological presuppositions underlying existentialist philosophy challenge conventional metaphysical assumptions', type: 'sentence' },
    { id: 5, text: 'Say the word: "DISPROPORTIONATELY"', expectedAnswer: 'disproportionately', type: 'word' },
    { id: 6, text: 'Analyze morphological complexity of "INCOMPREHENSIBLENESS"', expectedAnswer: 'in comprehens ible ness', type: 'phoneme' },
    { id: 7, text: 'Say the word: "MISCOMMUNICATION"', expectedAnswer: 'miscommunication', type: 'word' },
    { id: 8, text: 'Read: "The dialectical synthesis of thesis and antithesis constitutes the fundamental mechanism of Hegelian philosophy"', expectedAnswer: 'the dialectical synthesis of thesis and antithesis constitutes the fundamental mechanism of hegelian philosophy', type: 'sentence' },
  ],
  12: [
    { id: 1, text: 'Say the word: "FLOCCINAUCINIHILIPILIFICATION"', expectedAnswer: 'floccinaucinihilipilification', type: 'word' },
    { id: 2, text: 'Say the word: "PNEUMONOULTRAMICROSCOPICSILICOVOLCANOCONIOSIS"', expectedAnswer: 'pneumonoultramicroscopicsilicovolcanoconiosis', type: 'word' },
    { id: 3, text: 'Deconstruct the compound etymology of "ANTIDISESTABLISHMENTARIANISM"', expectedAnswer: 'anti dis establish ment arian ism', type: 'phoneme' },
    { id: 4, text: 'Read: "The teleological implications of deterministic cosmological models contradict libertarian conceptions of metaphysical free will"', expectedAnswer: 'the teleological implications of deterministic cosmological models contradict libertarian conceptions of metaphysical free will', type: 'sentence' },
    { id: 5, text: 'Say the word: "ELECTROENCEPHALOGRAPHICALLY"', expectedAnswer: 'electroencephalographically', type: 'word' },
    { id: 6, text: 'Analyze the derivational pathway of "DEINSTITUTIONALIZATION"', expectedAnswer: 'de institution al ization', type: 'phoneme' },
    { id: 7, text: 'Say the word: "COUNTERINTUITIVENESS"', expectedAnswer: 'counterintuitiveness', type: 'word' },
    { id: 8, text: 'Read: "The hermeneutical circle necessitates iterative interpretation wherein parts illuminate the whole and vice versa"', expectedAnswer: 'the hermeneutical circle necessitates iterative interpretation wherein parts illuminate the whole and vice versa', type: 'sentence' },
  ],
};

// Dyscalculia questions organized by grade (1-12)
export const dyscalculiaQuestionsByGrade: Record<number, Question[]> = {
  1: [
    { id: 1, text: 'Count from 1 to 10', expectedAnswer: '1 2 3 4 5 6 7 8 9 10', type: 'number' },
    { id: 2, text: 'What is 2 + 1?', expectedAnswer: '3', type: 'calculation' },
    { id: 3, text: 'What is 3 - 1?', expectedAnswer: '2', type: 'calculation' },
    { id: 4, text: 'What number comes after 5?', expectedAnswer: '6', type: 'number' },
    { id: 5, text: 'How many fingers do you have?', expectedAnswer: '10', type: 'number' },
    { id: 6, text: 'What is 1 + 1?', expectedAnswer: '2', type: 'calculation' },
    { id: 7, text: 'Count backwards from 5 to 1', expectedAnswer: '5 4 3 2 1', type: 'number' },
    { id: 8, text: 'What is 4 + 1?', expectedAnswer: '5', type: 'calculation' },
  ],
  2: [
    { id: 1, text: 'Count from 1 to 20', expectedAnswer: '1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20', type: 'number' },
    { id: 2, text: 'What is 5 + 3?', expectedAnswer: '8', type: 'calculation' },
    { id: 3, text: 'What is 10 - 4?', expectedAnswer: '6', type: 'calculation' },
    { id: 4, text: 'Count backwards from 10 to 1', expectedAnswer: '10 9 8 7 6 5 4 3 2 1', type: 'number' },
    { id: 5, text: 'What is 2 + 7?', expectedAnswer: '9', type: 'calculation' },
    { id: 6, text: 'What number comes after 15?', expectedAnswer: '16', type: 'number' },
    { id: 7, text: 'What is 8 - 3?', expectedAnswer: '5', type: 'calculation' },
    { id: 8, text: 'Skip count by 2s: 2, 4, 6...', expectedAnswer: '2 4 6 8 10', type: 'number' },
  ],
  3: [
    { id: 1, text: 'What is 12 + 15?', expectedAnswer: '27', type: 'calculation' },
    { id: 2, text: 'What is 25 - 13?', expectedAnswer: '12', type: 'calculation' },
    { id: 3, text: 'What is 3 × 4?', expectedAnswer: '12', type: 'calculation' },
    { id: 4, text: 'Count by 5s from 5 to 50', expectedAnswer: '5 10 15 20 25 30 35 40 45 50', type: 'number' },
    { id: 5, text: 'What is 6 × 7?', expectedAnswer: '42', type: 'calculation' },
    { id: 6, text: 'What is 100 - 45?', expectedAnswer: '55', type: 'calculation' },
    { id: 7, text: 'What is 8 × 5?', expectedAnswer: '40', type: 'calculation' },
    { id: 8, text: 'What is 12 ÷ 4?', expectedAnswer: '3', type: 'calculation' },
  ],
  4: [
    { id: 1, text: 'What is 156 + 287?', expectedAnswer: '443', type: 'calculation' },
    { id: 2, text: 'What is 500 - 234?', expectedAnswer: '266', type: 'calculation' },
    { id: 3, text: 'What is 12 × 11?', expectedAnswer: '132', type: 'calculation' },
    { id: 4, text: 'What is 144 ÷ 12?', expectedAnswer: '12', type: 'calculation' },
    { id: 5, text: 'Read the number: 5,007', expectedAnswer: 'five thousand seven', type: 'number' },
    { id: 6, text: 'What is 9 × 8?', expectedAnswer: '72', type: 'calculation' },
    { id: 7, text: 'What is 1000 - 375?', expectedAnswer: '625', type: 'calculation' },
    { id: 8, text: 'What is 81 ÷ 9?', expectedAnswer: '9', type: 'calculation' },
  ],
  5: [
    { id: 1, text: 'What is 2.5 + 3.7?', expectedAnswer: '6.2', type: 'calculation' },
    { id: 2, text: 'What is 1/2 + 1/4?', expectedAnswer: '3/4 or 0.75', type: 'calculation' },
    { id: 3, text: 'What is 15 × 15?', expectedAnswer: '225', type: 'calculation' },
    { id: 4, text: 'What is 25% of 100?', expectedAnswer: '25', type: 'calculation' },
    { id: 5, text: 'Read: 45,678', expectedAnswer: 'forty five thousand six hundred seventy eight', type: 'number' },
    { id: 6, text: 'What is 7.5 - 2.3?', expectedAnswer: '5.2', type: 'calculation' },
    { id: 7, text: 'What is 3/5 of 50?', expectedAnswer: '30', type: 'calculation' },
    { id: 8, text: 'What is 625 ÷ 25?', expectedAnswer: '25', type: 'calculation' },
  ],
  6: [
    { id: 1, text: 'What is -5 + 8?', expectedAnswer: '3', type: 'calculation' },
    { id: 2, text: 'What is 3/4 × 2/3?', expectedAnswer: '1/2 or 6/12', type: 'calculation' },
    { id: 3, text: 'What is 12² (12 squared)?', expectedAnswer: '144', type: 'calculation' },
    { id: 4, text: 'What is 50% of 250?', expectedAnswer: '125', type: 'calculation' },
    { id: 5, text: 'Convert 0.75 to a fraction', expectedAnswer: '3/4', type: 'number' },
    { id: 6, text: 'What is -3 × -4?', expectedAnswer: '12', type: 'calculation' },
    { id: 7, text: 'What is the square root of 64?', expectedAnswer: '8', type: 'calculation' },
    { id: 8, text: 'What is 2.5 × 4.2?', expectedAnswer: '10.5', type: 'calculation' },
  ],
  7: [
    { id: 1, text: 'Solve: 2x + 5 = 13, what is x?', expectedAnswer: '4', type: 'calculation' },
    { id: 2, text: 'What is 5³ (5 cubed)?', expectedAnswer: '125', type: 'calculation' },
    { id: 3, text: 'What is 15% of 400?', expectedAnswer: '60', type: 'calculation' },
    { id: 4, text: 'What is -12 ÷ -3?', expectedAnswer: '4', type: 'calculation' },
    { id: 5, text: 'Express 3/8 as a decimal', expectedAnswer: '0.375', type: 'number' },
    { id: 6, text: 'What is the absolute value of -17?', expectedAnswer: '17', type: 'calculation' },
    { id: 7, text: 'What is 2.4 × 0.5?', expectedAnswer: '1.2', type: 'calculation' },
    { id: 8, text: 'If y = 3x and x = 4, what is y?', expectedAnswer: '12', type: 'calculation' },
  ],
  8: [
    { id: 1, text: 'Solve: 3x - 7 = 14, what is x?', expectedAnswer: '7', type: 'calculation' },
    { id: 2, text: 'What is √(121)?', expectedAnswer: '11', type: 'calculation' },
    { id: 3, text: 'What is 2⁴ × 2³?', expectedAnswer: '128', type: 'calculation' },
    { id: 4, text: 'Calculate: (5 + 3) × (7 - 2)', expectedAnswer: '40', type: 'calculation' },
    { id: 5, text: 'What is 33⅓% of 90?', expectedAnswer: '30', type: 'calculation' },
    { id: 6, text: 'Simplify: 12/18', expectedAnswer: '2/3', type: 'number' },
    { id: 7, text: 'What is the slope of y = 2x + 5?', expectedAnswer: '2', type: 'calculation' },
    { id: 8, text: 'Solve: x² = 49, what is x?', expectedAnswer: '7 or -7', type: 'calculation' },
  ],
  9: [
    { id: 1, text: 'Factor: x² + 5x + 6', expectedAnswer: '(x+2)(x+3)', type: 'calculation' },
    { id: 2, text: 'What is sin(30°)?', expectedAnswer: '0.5 or 1/2', type: 'calculation' },
    { id: 3, text: 'Solve: 2x² = 50, what is x?', expectedAnswer: '5 or -5', type: 'calculation' },
    { id: 4, text: 'What is log₁₀(1000)?', expectedAnswer: '3', type: 'calculation' },
    { id: 5, text: 'Calculate the hypotenuse: legs are 3 and 4', expectedAnswer: '5', type: 'calculation' },
    { id: 6, text: 'What is 3! (3 factorial)?', expectedAnswer: '6', type: 'calculation' },
    { id: 7, text: 'Simplify: (x²)³', expectedAnswer: 'x⁶', type: 'calculation' },
    { id: 8, text: 'What is cos(60°)?', expectedAnswer: '0.5 or 1/2', type: 'calculation' },
  ],
  10: [
    { id: 1, text: 'Solve: log₂(x) = 5, what is x?', expectedAnswer: '32', type: 'calculation' },
    { id: 2, text: 'What is tan(45°)?', expectedAnswer: '1', type: 'calculation' },
    { id: 3, text: 'Factor: x² - 9', expectedAnswer: '(x+3)(x-3)', type: 'calculation' },
    { id: 4, text: 'What is the derivative of x³?', expectedAnswer: '3x²', type: 'calculation' },
    { id: 5, text: 'Calculate: 5! / 3!', expectedAnswer: '20', type: 'calculation' },
    { id: 6, text: 'Solve: e^x = 1, what is x?', expectedAnswer: '0', type: 'calculation' },
    { id: 7, text: 'What is the area of a circle with radius 5?', expectedAnswer: '25π or 78.54', type: 'calculation' },
    { id: 8, text: 'Simplify: ln(e⁴)', expectedAnswer: '4', type: 'calculation' },
  ],
  11: [
    { id: 1, text: 'What is the integral of 2x?', expectedAnswer: 'x² + C', type: 'calculation' },
    { id: 2, text: 'Solve: sin²(x) + cos²(x) = ?', expectedAnswer: '1', type: 'calculation' },
    { id: 3, text: 'What is lim(x→0) sin(x)/x?', expectedAnswer: '1', type: 'calculation' },
    { id: 4, text: 'Factor: x³ - 8', expectedAnswer: '(x-2)(x²+2x+4)', type: 'calculation' },
    { id: 5, text: 'What is the derivative of sin(x)?', expectedAnswer: 'cos(x)', type: 'calculation' },
    { id: 6, text: 'Calculate: C(5,2) combinations', expectedAnswer: '10', type: 'calculation' },
    { id: 7, text: 'What is e^(iπ) + 1?', expectedAnswer: '0', type: 'calculation' },
    { id: 8, text: 'Solve: dy/dx = 2x, find y', expectedAnswer: 'x² + C', type: 'calculation' },
  ],
  12: [
    { id: 1, text: 'What is ∫(1/x)dx?', expectedAnswer: 'ln|x| + C', type: 'calculation' },
    { id: 2, text: 'What is the Taylor series first term of e^x?', expectedAnswer: '1', type: 'calculation' },
    { id: 3, text: 'Solve: d²y/dx² = -y, general solution form?', expectedAnswer: 'A cos(x) + B sin(x)', type: 'calculation' },
    { id: 4, text: 'What is the determinant of [[1,2],[3,4]]?', expectedAnswer: '-2', type: 'calculation' },
    { id: 5, text: 'Calculate: lim(n→∞) (1 + 1/n)^n', expectedAnswer: 'e', type: 'calculation' },
    { id: 6, text: 'What is ∇·F for F = <x,y,z>?', expectedAnswer: '3', type: 'calculation' },
    { id: 7, text: 'Solve: ∫₀¹ x² dx', expectedAnswer: '1/3', type: 'calculation' },
    { id: 8, text: 'What is the Laplace transform of 1?', expectedAnswer: '1/s', type: 'calculation' },
  ],
};

export function getQuestionsForGrade(grade: number, sessionType: 'dyslexia' | 'dyscalculia'): Question[] {
  const gradeNum = Math.max(1, Math.min(12, grade));
  const questionBank = sessionType === 'dyslexia' ? dyslexiaQuestionsByGrade : dyscalculiaQuestionsByGrade;
  return questionBank[gradeNum] || questionBank[1];
}
